-- Add new Pattern enum values
ALTER TYPE "Pattern" ADD VALUE IF NOT EXISTS 'TRIES';
ALTER TYPE "Pattern" ADD VALUE IF NOT EXISTS 'BIT_MANIPULATION';
ALTER TYPE "Pattern" ADD VALUE IF NOT EXISTS 'INTERVALS';
ALTER TYPE "Pattern" ADD VALUE IF NOT EXISTS 'ADVANCED_GRAPHS';
ALTER TYPE "Pattern" ADD VALUE IF NOT EXISTS 'MATH_GEOMETRY';
ALTER TYPE "Pattern" ADD VALUE IF NOT EXISTS 'PREFIX_SUM';
